PL/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class AlumnoController : Controller
    {
        //[HttpGet] //Action VERB
        //public ActionResult GetAll() //Action Method
        //{
        //    ML.Alumno alumno = new ML.Alumno();
        //    ServiceReferenceAlumno.AlumnoClient servicioAlumno = new ServiceReferenceAlumno.AlumnoClient();
        //    var result = servicioAlumno.GetAll();

        //    if (result.Correct)
        //    {
        //        alumno.Alumnos = result.Objects.ToList();
        //    }
        //    else
        //    {
        //        ViewBag.Mensaje = "Ocurrio un error al consultar";
        //        return View();
        //    }
        //    return View(alumno);//Mandar a llamar a la vista, mostrar la vista(HTML)
        //}
        //public ActionResult Delete(int idAlumno)
        //{
        //    ML.Alumno alumno = new ML.Alumno();
        //    alumno.IdAlumno = idAlumno;
        //    ServiceReferenceAlumno.AlumnoClient servicioAlumno = new ServiceReferenceAlumno.AlumnoClient();

        //    var result = servicioAlumno.Delete(alumno);
        //    if (result.Correct)
        //    {

        //        ViewBag.Message = "El Alumno se elimino corectamente";
        //        return View("Modal");
        //    }
        //    else
        //    {
        //        ViewBag.Message = "El Alumno no se pudo eliminar " + result.ErrorMessage;
        //        return View("Modal");
        //    }

        //}

        //[HttpGet]
        //public ActionResult Form(int? idAlumno)
        //{
        //    ML.Alumno alumno = new ML.Alumno();


        //    //add o update
        //    if (idAlumno == null)
        //    {
        //        return View(alumno);
        //    }

        //    else
        //    {
        //        //update
        //        //muestra el formulario con la informacion del alumno
        //        ServiceReferenceAlumno.AlumnoClient servicioAlumno = new ServiceReferenceAlumno.AlumnoClient();
        //        var result = servicioAlumno.GetById(idAlumno.Value);
        //        if (result.Correct)
        //        {
        //            alumno = (ML.Alumno)result.Object;
        //            return View(alumno);
        //        }

        //        return View(alumno);
        //    }


        //}

        //[HttpPost]
        //public ActionResult Form(ML.Alumno alumno)
        //{
        //    //add o update
        //    if (alumno.IdAlumno == 0)
        //    {
        //        ServiceReferenceAlumno.AlumnoClient servicioAlumno = new ServiceReferenceAlumno.AlumnoClient();
        //        var result = servicioAlumno.Add(alumno);
        //        //add
        //        if (result.Correct)
        //        {

        //            ViewBag.Message = "El Alumno se inserto con exito";
        //            return View("Modal");
        //        }
        //        else
        //        {

        //            ViewBag.Message = "Error al insertar el Alumno" + result.ErrorMessage;
        //            return View("Modal");
        //        }
        //    }
        //    else
        //    {
        //        ServiceReferenceAlumno.AlumnoClient servicioAlumno = new ServiceReferenceAlumno.AlumnoClient();
        //        var result = servicioAlumno.Update(alumno);
        //        if (result.Correct)
        //        {
        //            ViewBag.Message = "Los datos del Alumno se actualizaron con exito";
        //        }
        //        else
        //        {
        //            ViewBag.Message = "Error al actualizar los datos del Alumno" + result.ErrorMessage;
        //        }

        //    }

        //    return View("Modal");
        //}
    }
}

PL/Views/Alumno/Form.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Alumno</h2>
            <h5>Ingrese los datos del alumno:</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <hr />
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Alumno", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Nombre)
                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })
                            @Html.ValidationMessageFor(model => model.Nombre, null, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.ApellidoPaterno)
                            @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control", @id = "txtApellidoPaterno" })
                            @Html.ValidationMessageFor(model => model.ApellidoPaterno, null, new { @class = "text-danger" })
                        </div>
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.ApellidoMaterno)
                            @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control", @id = "txtApellidoMaterno" })
                            @Html.ValidationMessageFor(model => model.ApellidoMaterno, null, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>


            }


        </div>
    </div>
</div>

PL/Views/Alumno/GetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="=col-md-12">
            <h2>Alumnos</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <h5>Seleccione Agregar para registrar un alumno</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1 ">
            @Html.ActionLink("Agregar", "Form", "Alumno", htmlAttributes: new { @class = "btn btn-success" })
        </div>
        <br> <br />
    </div>
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-responsive">
                <thead class="thead-dark">
                    <tr>
                        <td>Editar</td>
                        <td class="hidden">IdAlumno</td>
                        <td>Nombre</td>
                        <td>Apellido Paterno</td>
                        <td>Apellido Materno</td>

                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.Alumno alumno in Model.Alumnos)
                    {
                        <tr>
                            <td><a class="btn  btn-warning  glyphicon glyphicon-edit" href="@Url.Action("Form", "Alumno", new { IdAlumno = alumno.IdAlumno })"></a></td>
                            <td class="hidden">@alumno.IdAlumno</td>
                            <td>@alumno.Nombre</td>
                            <td>@alumno.ApellidoPaterno</td>
                            <td>@alumno.ApellidoMaterno</td>
                            <td><a class="btn btn-danger glyphicon glyphicon-trash " href="@Url.Action("Delete", "Alumno", new { IdAlumno = alumno.IdAlumno })" onclick="return confirm('¿Estas seguro que deseas eliminar este registro?');"></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

PL/Views/Alumno/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>