PL/Controllers/MateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;


namespace PL.Controllers
{
    public class MateriaController : Controller
    {
        [HttpGet]
        public ActionResult GetAll() //Action Method
        {
            ML.Result resultMateria = new ML.Result();
            resultMateria.Objects = new List<Object>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:6803/api/");

                var responseTask = client.GetAsync("Materia/GetAll");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {

                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        ML.Materia resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Materia>(resultItem.ToString());
                        resultMateria.Objects.Add(resultItemList);
                    }

                }
            }
            ML.Materia materia = new ML.Materia();
            materia.Materias = resultMateria.Objects;
            return View(materia);//Mandar a llamar a la vista, mostrar la vista(HTML)
        }
        [HttpGet]
        public ActionResult Form(int? IdMateria)
        {
            ML.Materia materia = new ML.Materia();
            ML.Result resultmateria = BL.Materia.GetAll();

            if (IdMateria == null)
            {
                return View(materia);
            }
            else //esto es para el update
            {
                ML.Result result = new ML.Result();
                using (var client = new HttpClient())
                    try
                    {
                        client.BaseAddress = new Uri("http://localhost:6803/api/");
                        var responseTask = client.GetAsync("Materia/GetById/" + IdMateria);
                        responseTask.Wait();
                        var resultAPI = responseTask.Result;
                        if (resultAPI.IsSuccessStatusCode)
                        {
                            var readTask = resultAPI.Content.ReadAsAsync<ML.Result>();
                            readTask.Wait();
                            ML.Materia resultItemList = new ML.Materia();
                            resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Materia>(readTask.Result.Object.ToString());
                            result.Object = resultItemList;

                            materia = ((ML.Materia)result.Object);
                            materia.Materias = resultmateria.Objects;
                            return View(materia);

                        }
                        else
                        {
                            result.Correct = false;
                            result.ErrorMessage = "No existen registros en la tabla ";
                            return View("Modal");
                        }
                    }

                    catch (Exception ex)
                    {
                        result.Correct = false;
                        result.ErrorMessage = ex.Message;
                    }

                return View();
            }
        }
        [HttpPost]
        public ActionResult Form(ML.Materia materia)
        {
            ML.Result result = new ML.Result();
            if (ModelState.IsValid)
            {
                if (materia.IdMateria == 0)
                {
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri("http://localhost:6803/api/");

                        //HTTP POST
                        var postTask = client.PostAsJsonAsync<ML.Materia>("Materia/Add", materia);
                        postTask.Wait();

                        var resultAseguradora = postTask.Result;
                        if (resultAseguradora.IsSuccessStatusCode)
                        {
                            ViewBag.Mensaje = "La materia se registro correctamente";
                        }
                        else
                        {
                            ViewBag.Mensaje = "La materia no se ha registrado correctamente" + result.ErrorMessage;
                          
                        }
                    }
                }
            }
            
            else
            {
                using (var client = new HttpClient())
                {

                    client.BaseAddress = new Uri("http://localhost:6803/api/");


                    var postTask = client.PostAsJsonAsync<ML.Materia>("Materia/Update/" + materia.IdMateria, materia);
                    postTask.Wait();

                    var resultmateria = postTask.Result;

                    if (resultmateria.IsSuccessStatusCode)
                    {
                        ViewBag.Mensaje = "La materia se ha actualizado correctamente";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Mensaje = "La materia no se ha actualizado correctamente" + result.ErrorMessage;
                        return PartialView("Modal");
                    }
                }


            }

            return PartialView("Modal");
        }
        public ActionResult Delete(ML.Materia materia)
        {

            ML.Result resultmateria = new ML.Result();
            int IdMateria = materia.IdMateria;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:6803/api/");

                //HTTP POST
                var postTask = client.GetAsync("Materia/Delete/" + IdMateria);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    ViewBag.Message = "La materia ha sido eliminada";
                    return View("Modal");
                }
                else
                {
                    ViewBag.Message = "La materia no pudo ser eliminada" + resultmateria.ErrorMessage;
                    return View("Modal");
                }
            }

            return View();
        }
    }
}

PL/Views/Materia/Form.cshtml
@model ML.Materia
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Materia</h2>
            <h5>Ingrese los datos de la Materia:</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <hr />
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Materia", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.IdMateria, new { @class = "hidden" })
                            @Html.TextBoxFor(model => model.IdMateria, new { @class = "hidden form-control", autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.IdMateria)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Nombre)
                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre", @autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Costo)
                            @Html.TextBoxFor(model => model.Costo, new { @class = "form-control", @id = "txtCosto", @autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.Costo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>


            }


        </div>
    </div>
</div>

PL/Views/Materia/GetAll.cshtml
@model ML.Materia
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="=col-md-12">
            <h2>Materias</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <h5>Seleccione Agregar para registrar una Materia</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1 ">
            @Html.ActionLink("Agregar", "Form", "Materia", htmlAttributes: new { @class = "btn btn-success" })
        </div>
        <br> <br />
    </div>
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-responsive">
                <thead class="thead-dark">
                    <tr>
                        <td>Editar</td>
                        <td class="hidden">IdMateria</td>
                        <td>Nombre</td>
                        <td>Costo</td>

                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.Materia materia in Model.Materias)
                    {
                        <tr>
                            <td><a class="btn  btn-warning  glyphicon glyphicon-edit" href="@Url.Action("Form", "Materia", new { IdMateria = materia.IdMateria })"></a></td>
                            <td class="hidden">@materia.IdMateria</td>
                            <td>@materia.Nombre</td>
                            <td>@materia.Costo</td>
                            <td><a class="btn btn-danger glyphicon glyphicon-trash " href="@Url.Action("Delete", "Materia", new { IdMateria = materia.IdMateria  })" onclick="return confirm('¿Estas seguro que deseas eliminar este registro?');"></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

PL/Views/Materia/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>